[package]
name = "hello"
version = "0.1.0"
authors = ["bit-meddler <RichH@Beacon-Optical.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
